# -----------------------------------------------------------------------------
# application - this is the name of the application
# -----------------------------------------------------------------------------
application: team16-tau
# -----------------------------------------
# the version of the application we create
# -----------------------------------------
version: 1
# -----------------------------------------
# programming language
# -----------------------------------------
runtime: python27
# -----------------------------------------
# python sub version
# -----------------------------------------
api_version: 1
# ---------------------------------------------------------------------
# threadsafe - to prevent collision between calls to the application
#              from different clients
# ---------------------------------------------------------------------
threadsafe: true
# ---------------------------------------------------------------------
# handlers - define an application file for each URL we get
# ---------------------------------------------------------------------
handlers:
- url: /images
  static_dir: images

#- url: /favicon\.ico
#  static_files: images/favicon.ico
#  upload: images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: main.app
  login: required
  
# ---------------------------------------------------------------------
# libraries in use 
# ---------------------------------------------------------------------
libraries:
- name: jinja2
  version: latest
- name: MySQLdb
  version: latest
